config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  get 'access_policies/create'

  get 'resources/index'

  root to: redirect(path: '/projects')

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
               sessions: 'users/sessions'
             }

  ## User profile section routes
  resource :profile, only: [:show, :update] do
    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :password, only: [:show, :update]
      resource :plgrid, only: [:show, :destroy]
      resources :compute_site_proxy
    end
  end

  resources :projects, except: [:edit, :update], constraints: { id: /.+/ } do
    scope module: :projects do
      resources :pipelines do
        scope module: :pipelines do
          resources :computations, only: [:show, :update]
        end
      end
    end
  end

  namespace :api do
    resources :pdp, only: :index
    resources :sessions, only: :create
    resources :policies, only: [:create, :index]
    delete 'policies', to: 'policies#destroy'
    resources :policy_entities, only: :index
    # LOBCDER API webhook
    post 'staging' => 'staging#notify'
    resources :projects, only: :index do
      scope module: :projects do
        resources :pipelines, only: :index do
          scope module: :pipelines do
            resources :computations, only: [:index, :show, :create]
          end
        end
      end
    end
  end

  resources :services do
    scope module: :services do
      resources :local_policies
      resources :global_policies
    end
  end
  resources :groups do
    scope module: :groups do
      resources :user_groups, only: [:create, :destroy]
    end
  end
  resources :resources, only: :index do
    scope module: :resources do
      resources :access_policies, only: [:create, :destroy]
      resources :resource_managers, only: [:create, :destroy]
    end
  end
  resources :cloud_resources, only: :index

  # Help
  get 'help' => 'help#index'
  get 'help/:category/:file' => 'help#show',
      as: :help_page,
      constraints: { category: /.*/, file: %r{[^/\.]+} }

  # File Store
  get 'file_store' => 'file_store#index'

  namespace :admin do
    resources :users
  end

  # Sidekiq monitoring
  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    namespace :admin do
      resource :job, only: :show
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end
# rubocop:enable BlockLength

app/views/layouts/left_menu/_administration.html.haml
- if policy(User).manage_users? || policy(:job).show?
  = nav_link controller: [:account_confirmation, :jobs] do
    %a
      = icon('gears')
      = t('.title')
      %span.fa.fa-chevron-down
    %ul.nav.child_menu
      - if policy(User).manage_users?
        = nav_link controller: :users, active_class: 'current-page' do
          = link_to admin_users_path do
            = t('.users')
            - if User.new_accounts.count.positive?
              .pull-right
                = icon('exclamation-triangle')
              .clearfix
      - if policy(:job).show?
        = nav_link controller: :jobs, active_class: 'current-page' do
          = link_to(t('.jobs'), admin_job_path)

app/views/layouts/left_menu/_help.html.haml
= nav_link controller: :help do
  %a
    = icon('question-circle')
    = t('.title')
    %span.fa.fa-chevron-down
  %ul.nav.child_menu
    = nav_tab :file, 'sessions', active_class: 'current-page' do
      = link_to t('.sessions'), help_page_path(category: 'api', file: 'sessions')
    = nav_tab :file, 'pdp', active_class: 'current-page' do
      = link_to t('.pdp'), help_page_path(category: 'api', file: 'pdp')
    = nav_tab :file, 'policies', active_class: 'current-page' do
      = link_to t('.policies'), help_page_path(category: 'api', file: 'policies')

app/views/layouts/left_menu/_research.html.haml
= nav_link controller: [:projects, :file_store, :pipelines] do
  %a
    = icon('flask')
    = t('.title')
    %span.fa.fa-chevron-down
  %ul.nav.child_menu
    = nav_link controller: [:projects, :pipelines, :computations], active_class: 'current-page' do
      = link_to projects_path do
        = t('.projects')
    = nav_link controller: :cloud_resources, active_class: 'current-page' do
      = link_to cloud_resources_path, data: { turbolinks: false } do
        = t('.cloud_resources')

app/views/layouts/left_menu/_settings.html.haml
= nav_link controller: [:profiles, :accounts, :passwords, :plgrids, :services, :local_policies, :global_policies, :groups, :access_policies, :resources] do
  %a
    = icon('sliders')
    = t('.title')
    %span.fa.fa-chevron-down
  %ul.nav.child_menu
    = nav_link controller: [:profiles, :accounts, :passwords, :plgrids], active_class: 'current-page' do
      = link_to(t('.profile'), profile_path)
    = nav_link controller: [:services, :local_policies, :global_policies], active_class: 'current-page' do
      = link_to(t('.services'), services_path)
    = nav_link controller: :groups, active_class: 'current-page' do
      = link_to(t('.groups'), groups_path)