config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  get 'access_policies/create'

  get 'resources/index'

  root to: redirect(path: '/projects')

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
               sessions: 'users/sessions'
             }

  ## User profile section routes
  resource :profile, only: [:show, :update] do
    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :password, only: [:show, :update]
      resource :plgrid, only: [:show, :destroy]
      resources :compute_site_proxy
    end
  end

  resources :projects, except: [:edit, :update], constraints: { id: /.+/ } do
    scope module: :projects do
      resources :pipelines do
        scope module: :pipelines do
          resources :computations, only: [:show, :update]
        end
      end
    end
  end

  namespace :api do
    resources :pdp, only: :index
    resources :sessions, only: :create
    resources :policies, only: [:create, :index]
    delete 'policies', to: 'policies#destroy'
    resources :policy_entities, only: :index
    # LOBCDER API webhook
    post 'staging' => 'staging#notify'
    resources :projects, only: :index do
      scope module: :projects do
        resources :pipelines, only: :index do
          scope module: :pipelines do
            resources :computations, only: [:index, :show, :create]
          end
        end
      end
    end
  end

  resources :services do
    scope module: :services do
      resources :local_policies
      resources :global_policies
    end
  end
  resources :groups do
    scope module: :groups do
      resources :user_groups, only: [:create, :destroy]
    end
  end
  resources :resources, only: :index do
    scope module: :resources do
      resources :access_policies, only: [:create, :destroy]
      resources :resource_managers, only: [:create, :destroy]
    end
  end
  resources :cloud_resources, only: :index

  # Help
  get 'help' => 'help#index'
  get 'help/:category/:file' => 'help#show',
      as: :help_page,
      constraints: { category: /.*/, file: %r{[^/\.]+} }

  # File Store
  get 'file_store' => 'file_store#index'

  namespace :admin do
    resources :users
  end

  # Sidekiq monitoring
  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    namespace :admin do
      resource :job, only: :show
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end
# rubocop:enable BlockLength

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  include CheckExistenceConcern

  has_many :user_groups,
           autosave: true,
           dependent: :destroy
  has_many :users, through: :user_groups
  has_many :access_policies, dependent: :destroy
  has_many :resource_managers, dependent: :destroy
  has_many :parent_group_relationship,
           class_name: 'GroupRelationship',
           foreign_key: 'child_id',
           dependent: :destroy,
           inverse_of: :child
  has_many :child_group_relationship,
           class_name: 'GroupRelationship',
           foreign_key: 'parent_id',
           dependent: :destroy,
           inverse_of: :parent
  has_many :parents,
           through: :parent_group_relationship,
           source: :parent
  has_many :children,
           through: :child_group_relationship,
           source: :child

  validates :name, presence: true
  validates :name, uniqueness: true
  validate :at_least_one_owner

  def ancestors
    parents + parents.map(&:ancestors).flatten
  end

  def offspring
    children + children.map(&:offspring).flatten
  end

  def offspring_candidates
    Group.all - ancestors - [self]
  end

  def all_users
    (users + offspring.map(&:users).flatten).uniq
  end

  def members
    users.joins(:user_groups).where(user_groups: { owner: false }).distinct
  end

  def owners
    users.joins(:user_groups).where(user_groups: { owner: true }).distinct
  end

  private

  def at_least_one_owner
    errors.add(:owner_ids, 'At least one group owner is required') unless user_groups.any?(&:owner)
  end
end

app/controllers/groups/user_groups_controller.rb
# frozen_string_literal: true

module Groups
  class UserGroupsController < ApplicationController
    before_action :find_group_and_authorize

    def create
      attrs = permitted_attributes(UserGroup)
      owner = attrs[:owner] || false
      User.where(id: attrs[:user_id]).each do |user|
        user_group(user).owner ||= owner
      end

      @group.save ? redirect_to_group : render_errors
    end

    def destroy
      user_group = @group.user_groups.find(params[:id])
      authorize(user_group)

      if last_admin?(user_group)
        redirect_to_group(alert: I18n.t('errors.user_groups.last_owner'))
      else
        user_group.destroy!
        redirect_to_group
      end
    end

    private

    def user_group(user)
      @group.user_groups.detect { |ug| ug.user_id == user.id } ||
        @group.user_groups.build(user: user)
    end

    def redirect_to_group(options = {})
      redirect_to group_path(@group), options
    end

    def render_errors
      render('groups/show', status: :bad_request)
    end

    def last_admin?(user_group)
      @group.user_groups.
        where(owner: true).
        where.not(id: user_group.id).
        count.zero?
    end

    def find_group_and_authorize
      @group = Group.includes(:user_groups).find(params[:group_id])
      authorize(@group, :update?)
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :find_group_and_authorize,
                only: [:destroy, :update]

  def index
    @groups = policy_scope(Group).order(:name)
  end

  def show
    @group = Group.includes(:users, :children, :parents).find(params[:id])
    authorize(@group)
  end

  def new
    @group = Group.new
    authorize(@group)
  end

  def create
    @group = Group.new(permitted_attributes(Group))
    @group.user_groups.build(user: current_user, owner: true)
    authorize(@group)

    if @group.save
      redirect_to(group_path(@group))
    else
      render(:new)
    end
  end

  def edit
    @group = Group.includes(:parents).find(params[:id])
    authorize(@group)
  end

  def update
    if @group.update_attributes(permitted_attributes(@group))
      redirect_to(group_path(@group))
    else
      render(:edit, status: :bad_request)
    end
  rescue ActiveRecord::RecordInvalid
    @group.errors.add(:child_ids,
                      I18n.t('activerecord.errors.models.group.child_ids.cycle'))
    render(:edit, status: :bad_request)
  end

  def destroy
    @group.destroy
    redirect_to(groups_path)
  end

  private

  def find_group_and_authorize
    @group = Group.find(params[:id])
    authorize(@group)
  end
end

app/views/groups/_edit_help.en.haml
.x_panel
  .x_title
    %h2 Editing a group
    .clearfix
  .x_content
    %p
      Here you can change group properties, including its name, membership and nesting status.
    %p
      Note that groups may be included in other groups, forming a treelike hierarchy. To include this group in
      another group, click the
      %b Directly included group
      textbox and select the group you want. All members of this group will then be treated as members of the
      parent group for the purposes of request authorization.
    %p
      You can ensure that all newly created user accounts are automatically assigned to this group by clicking the
      checkbox provided.

app/views/groups/_form.html.haml
= simple_form_for(group) do |f|
  = f.error_notification
  = f.input :name
  = f.association :children, collection: @group.offspring_candidates
  = f.association :parents, disabled: true
  = f.input :default

  .ln_solid
  .form-group
    .col-md-6.col-md-offset-3
      = f.button :submit, class: 'btn btn-success'
:javascript
  $("#group_child_ids").select2({ theme: "bootstrap" });
  $("#group_parent_ids").select2({ theme: "bootstrap" });

app/views/groups/_group.html.haml
%tr
  %td
    = link_to group.name, group
  %td
    - if policy(group).edit?
      = link_to([:edit, group], title: t('.edit'), class: 'edit') do
        = icon('edit')
    - if policy(group).destroy?
      = link_to(group_path(group), title: t('.remove'),
          method: :delete,
          class: 'delete',
          data: { confirm: t('are_you_sure') }) do
        = icon('remove')

app/views/groups/_index_help.en.haml
.x_panel
  .x_title
    %h2 User groups
    .clearfix
  .x_content
    %p
      This panel presents a list of user groups which have been defined in the system. User groups are an important
      component of the EurValve security infrastructure: some requests and operations may be restricted to members
      of a specific group.
    %p
      You can add a new group by clicking the
      %b Register a new group
      button. You can also review properties of existing groups by clicking their names.
    %p
      Management actions are available to group owners - if you are the owner of a group, the system will display
      action buttons enabling you to edit that group's properties or delete it entirely.

app/views/groups/_new_help.en.haml
.x_panel
  .x_title
    %h2 Creating a group
    .clearfix
  .x_content
    %p
      To create a group, you must provide a unique name and a preliminary list of members.
    %p
      Members flagged as "owners" will be allowed to manage the group and change its properties.
    %p
      Note that groups may be included in other groups, forming a treelike hierarchy. To include this group in
      another group, click the
      %b Directly included group
      textbox and select the group you want. All members of this group will then be treated as members of the
      parent group for the purposes of request authorization.
    %p
      You can ensure that all newly created user accounts are automatically assigned to this group by clicking the
      checkbox provided.

app/views/groups/_show_help.en.haml
.x_panel
  .x_title
    %h2 Group management panel
    .clearfix
  .x_content
    %p
      This is the group management panel where you can edit the properties of your groups. A group
      must have a name and may consist of multiple users. Assigning users to groups is important from
      the point of view of resource sharing (as resources can be shared with groups).
    %p
      Use the action buttons displayed in the title bar to edit group properties, remove the group altogether
      or navigate back to the group selection screen.

app/views/groups/edit.html.haml
.row
  .col-md-8
    .x_panel
      .x_title
        %h2
          = t '.title'
          %small= t '.subtitle'

        %ul.nav.navbar-right.panel_toolbox
          %li
            = link_to(group_path(@group), class: 'back') do
              = icon("hand-o-left", title: t('.back'))
        .clearfix

      .x_content
        = render partial: 'form', locals: { group: @group }
  .col-md-4
    = render 'edit_help'

app/views/groups/index.html.haml
%h1
  = t '.title'
  .pull-right
    %a{ href: url_for(new_group_path), title: t('.add'), class: 'btn btn-success' }
      = icon('plus', t('.add'))
.col-md-8
  .x_panel
    .x_content
      - if @groups.exists?
        %table.table.table-striped
          %thead
            %tr
              %th= t 'group.name'
              %th
          #tbody
            = render @groups
      - else
        %p= t '.nothing'
.col-md-4
  = render 'index_help'

app/views/groups/new.html.haml
.row
  .col-md-8
    .x_panel
      .x_title
        %h2
          = t '.title'
          %small= t '.subtitle'

        %ul.nav.navbar-right.panel_toolbox
          %li
            = link_to(groups_path) do
              = icon("hand-o-left", title: t('.back'))
        .clearfix

      .x_content
        = render partial: 'form', locals: { group: @group }
  .col-md-4
    = render 'new_help'

app/views/groups/show.html.haml
.row
  .col-md-8
    .x_panel
      .x_title
        %h2= @group.name

        %ul.nav.navbar-right.panel_toolbox
          %li
            = link_to(groups_path, class: 'back') do
              = icon('hand-o-left', title: t('.back'))
          - if policy(@group).edit?
            %li
              = link_to(edit_group_path(@group), class: 'edit') do
                = icon('edit', title: t('edit'))
          - if policy(@group).destroy?
            %li
              = link_to(group_path(@group),
                method: :delete, class: 'delete',
                data: { confirm: t('are_you_sure') }) do
                = icon('remove', title: t('remove'))
        .clearfix

      .x_content
        %table.table
          %tbody
            %tr
              %td= t('simple_form.labels.group.name')
              %td= @group.name
            %tr
              %td= t('simple_form.labels.group.children')
              %td= pill_list(@group.children)
            %tr
              %td= t('simple_form.labels.group.parents')
              %td= pill_list(@group.parents)
            %tr
              %td= t('simple_form.labels.group.ancestors')
              %td= pill_list(@group.ancestors)
            %tr
              %td= t('simple_form.labels.group.offspring')
              %td= pill_list(@group.offspring)
            %tr
              %td= t('simple_form.labels.group.all_users')
              %td= pill_list(@group.all_users) { |user| raw_user_name(user) }
            %tr
              %td= t('simple_form.labels.group.default')
              %td= @group.default
        %hr
    .x_panel
      .x_title
        %h2= t('.members')
        .clearfix
      .x_content
        = render('user_groups/index', user_groups: @group.user_groups)
  - if policy(@group).update?
    .col-md-4
      = render 'show_help'
      .x_panel
        .x_title= t('.add')
        .x_content
          = render('user_groups/form')