config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  get 'access_policies/create'

  get 'resources/index'

  root to: redirect(path: '/projects')

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
               sessions: 'users/sessions'
             }

  ## User profile section routes
  resource :profile, only: [:show, :update] do
    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :password, only: [:show, :update]
      resource :plgrid, only: [:show, :destroy]
      resources :compute_site_proxy
    end
  end

  resources :projects, except: [:edit, :update], constraints: { id: /.+/ } do
    scope module: :projects do
      resources :pipelines do
        scope module: :pipelines do
          resources :computations, only: [:show, :update]
        end
      end
    end
  end

  namespace :api do
    resources :pdp, only: :index
    resources :sessions, only: :create
    resources :policies, only: [:create, :index]
    delete 'policies', to: 'policies#destroy'
    resources :policy_entities, only: :index
    # LOBCDER API webhook
    post 'staging' => 'staging#notify'
    resources :projects, only: :index do
      scope module: :projects do
        resources :pipelines, only: :index do
          scope module: :pipelines do
            resources :computations, only: [:index, :show, :create]
          end
        end
      end
    end
  end

  resources :services do
    scope module: :services do
      resources :local_policies
      resources :global_policies
    end
  end
  resources :groups do
    scope module: :groups do
      resources :user_groups, only: [:create, :destroy]
    end
  end
  resources :resources, only: :index do
    scope module: :resources do
      resources :access_policies, only: [:create, :destroy]
      resources :resource_managers, only: [:create, :destroy]
    end
  end
  resources :cloud_resources, only: :index

  # Help
  get 'help' => 'help#index'
  get 'help/:category/:file' => 'help#show',
      as: :help_page,
      constraints: { category: /.*/, file: %r{[^/\.]+} }

  # File Store
  get 'file_store' => 'file_store#index'

  namespace :admin do
    resources :users
  end

  # Sidekiq monitoring
  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    namespace :admin do
      resource :job, only: :show
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end
# rubocop:enable BlockLength

app/views/resources/_form.html.haml
= simple_form_for(resource, url: url) do |f|
  = f.error_notification
  = f.input :name
  = f.input(:pretty_path, input_html: { value: resource&.pretty_path || '/' }, as: :string)
  .ln_solid
  .form-group
    .col-md-6.col-md-offset-3
      = f.button :submit, class: 'btn btn-success'

app/views/resources/_index_help.en.haml
.x_panel
  .x_title
    %h2 EurValve web resources
    .clearfix
  .x_content
    %p
      This panel presents a list of available web resources. A web resource may be an arbitrary object (usually
      a data file) which is available under a specific URI. Web resources may have associated security policies
      which define who and when can access the given resource.

app/views/resources/_managers.html.haml
.x_panel
  .x_title
    %h2= t('.title')
    .clearfix
  .x_content
    = render('resource_managers/index', model: @managers_model)
    %hr
    = render('resource_managers/form', model: @managers_model)

app/views/resources/_resource.html.haml
%tr
  %td= resource.name
  %td= resource.uri
  %td
    = link_to(new_access_policy_path(resource_id: resource.id),
       title: t('.edit'), class: 'edit') do
      = icon('edit')

app/views/resources/index.html.haml
%h1
  = t('.title')
.col-md-8
  .x_panel
    .x_content
      - if @resources.exists?
        %table.table
          %thead
            %tr
              %th= t('.name')
              %th= t('.uri')
              %th
            = render @resources
      - else
        %p= t('.nothing')
.col-md-4
  =render 'index_help'