config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  get 'access_policies/create'

  get 'resources/index'

  root to: redirect(path: '/projects')

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations',
               sessions: 'users/sessions'
             }

  ## User profile section routes
  resource :profile, only: [:show, :update] do
    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :password, only: [:show, :update]
      resource :plgrid, only: [:show, :destroy]
      resources :compute_site_proxy
    end
  end

  resources :projects, except: [:edit, :update], constraints: { id: /.+/ } do
    scope module: :projects do
      resources :pipelines do
        scope module: :pipelines do
          resources :computations, only: [:show, :update]
        end
      end
    end
  end

  namespace :api do
    resources :pdp, only: :index
    resources :sessions, only: :create
    resources :policies, only: [:create, :index]
    delete 'policies', to: 'policies#destroy'
    resources :policy_entities, only: :index
    # LOBCDER API webhook
    post 'staging' => 'staging#notify'
    resources :projects, only: :index do
      scope module: :projects do
        resources :pipelines, only: :index do
          scope module: :pipelines do
            resources :computations, only: [:index, :show, :create]
          end
        end
      end
    end
  end

  resources :services do
    scope module: :services do
      resources :local_policies
      resources :global_policies
    end
  end
  resources :groups do
    scope module: :groups do
      resources :user_groups, only: [:create, :destroy]
    end
  end
  resources :resources, only: :index do
    scope module: :resources do
      resources :access_policies, only: [:create, :destroy]
      resources :resource_managers, only: [:create, :destroy]
    end
  end
  resources :cloud_resources, only: :index

  # Help
  get 'help' => 'help#index'
  get 'help/:category/:file' => 'help#show',
      as: :help_page,
      constraints: { category: /.*/, file: %r{[^/\.]+} }

  # File Store
  get 'file_store' => 'file_store#index'

  namespace :admin do
    resources :users
  end

  # Sidekiq monitoring
  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    namespace :admin do
      resource :job, only: :show
    end
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end
# rubocop:enable BlockLength

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  has_many :resources, dependent: :destroy
  has_many :access_methods, dependent: :destroy
  has_many :service_ownerships, dependent: :destroy
  has_many :users, through: :service_ownerships

  validates :uri,
            presence: true,
            uniqueness: true,
            format: { with: /\A#{URI::DEFAULT_PARSER.make_regexp}\z/ }
  validates :users,
            presence: true
  validate :uri_does_not_end_with_slash

  before_validation :reject_blank_aliases
  before_validation :check_if_not_override_uri
  before_validation :check_if_not_overridden_by_uri

  before_validation :check_uri_aliases_format
  before_validation :check_uri_aliases_uniqueness
  before_validation :check_uri_aliases_same
  before_validation :check_if_not_overridden_by_alias
  before_validation :check_if_alias_not_overridden

  before_create :generate_token

  def to_s
    uri
  end

  private

  def generate_token
    self.token ||= loop do
      random_token = SecureRandom.hex
      break random_token unless Service.exists?(token: random_token)
    end
  end

  def uri_does_not_end_with_slash
    errors.add(:uri, 'Service URI cannot end with a slash') if uri.present? && uri.end_with?('/')
  end

  def reject_blank_aliases
    uri_aliases.reject!(&:blank?)
  end

  def check_override(uri)
    return false if uri.blank?
    sc = Service.where('uri LIKE ?', "#{uri}%").where.not(id: id)

    # Regexp used to eliminate false-positives for TLDs (e.g. .co vs .com)
    sc.any? { |s| (s.uri =~ %r{\A.*:\/\/.*\/.*\z}) }
  end

  def check_if_not_override_uri
    return unless check_override(uri)
    errors.add(:uri, I18n.t('activerecord.errors.models.service.uri.override'))
  end

  def check_if_not_overridden_by_uri
    return unless uri.present? && any_other? { |s| uri.start_with? "#{s.uri}/" }
    errors.add(:uri, I18n.t('activerecord.errors.models.service.uri.overridden'))
  end

  def check_overridden(op1, op2)
    op1.any? { |a| a == op2 || a.start_with?("#{op2}/") || op2.start_with?("#{a}/") }
  end

  def check_if_not_overridden_by_alias
    return unless uri.present? && any_other? { |s| check_overridden(uri_aliases, s.uri) }
    errors.add(:uri_aliases,
               I18n.t('activerecord.errors.models.service.uri_aliases.overridden'))
  end

  def check_if_alias_not_overridden
    return unless uri.present? && any_other? { |s| check_overridden(s.uri_aliases, uri) }
    errors.add(:uri_aliases,
               I18n.t('activerecord.errors.models.service.uri_aliases.overridden'))
  end

  def any_other?
    Service.where.not(id: id).any? { |s| yield(s) }
  end

  def duplicate_aliases?(la)
    sql = <<~SQL
      EXISTS (SELECT * FROM (SELECT unnest(services.uri_aliases))
       x(uri_aliases) WHERE x.uri_aliases LIKE ?)
    SQL
    Service.where(sql, "#{la}%").where.not(id: id).count.positive?
  end

  def duplicate_uri?(u)
    Service.where('uri LIKE ?', "#{u}%").where.not(id: id).count.positive?
  end

  def check_uri_aliases_format
    return unless uri_aliases.any? { |u| u !~ /\A#{URI.parser.make_regexp}\z/ }
    errors.add(:uri_aliases, I18n.t('activerecord.errors.models.service.uri_aliases.format'))
  end

  def check_uri_aliases_same
    return unless uri_aliases.any? { |u| u == uri }
    errors.add(:uri_aliases,
               I18n.t('activerecord.errors.models.service.uri_aliases.urialiassame'))
  end

  # Checks if any of the aliases overlaps with any of the services' aliases
  def check_uri_aliases_uniqueness
    return unless uri_aliases.any? { |u| duplicate_aliases?(u) }
    errors.add(:uri_aliases, I18n.t('activerecord.errors.models.service.uri_aliases.uniqueness'))
  end
end

app/controllers/api/service_controller.rb
# frozen_string_literal: true

module Api
  class ServiceController < Api::ApplicationController
    attr_reader :service

    before_action :authenticate_service!

    private

    def authenticate_service!
      @service = token && Service.find_by(token: token)

      service_invalid! unless @service
    end

    def token
      request.headers['HTTP_X_SERVICE_TOKEN']
    end

    def service_invalid!
      head :unauthorized,
           'WWW-Authenticate' => 'X-SERVICE-TOKEN header is invalid'
    end
  end
end

app/controllers/services/global_policies_controller.rb
# frozen_string_literal: true

module Services
  class GlobalPoliciesController < Services::PoliciesController
    private

    def resource_type
      :global
    end

    def resource_path(service, resource)
      service_global_policy_path(service, resource)
    end

    def resources_path(service)
      service_global_policies_path(service)
    end
  end
end

app/controllers/services/local_policies_controller.rb
# frozen_string_literal: true

module Services
  class LocalPoliciesController < Services::PoliciesController
    def resource_type
      :local
    end

    def resource_path(service, resource)
      service_local_policy_path(service, resource)
    end

    def resources_path(service)
      service_local_policies_path(service)
    end
  end
end

app/controllers/services/policies_controller.rb
# frozen_string_literal: true

module Services
  class PoliciesController < ApplicationController
    before_action :load_service
    before_action :find_and_authorize, only: [:show, :edit, :update, :destroy]

    def index
      @resources = @service.resources.where(resource_type: resource_type)
    end

    def new
      @resource = Resource.new(service: @service, resource_type: resource_type)
      authorize(@resource)
    end

    def show
      @model = ResourceAccessPoliciesDecorator.
               new(current_user, @resource, AccessPolicy.new)

      @managers_model = ResourceManagersDecorator.
                        new(@resource, ResourceManager.new)
    end

    def create
      create_and_authorize_resource

      if @resource.save
        redirect_to(resource_path(@service, @resource))
      else
        render(:new)
      end
    end

    def edit; end

    def update
      if @resource.update_attributes(permitted_attributes(@resource))
        redirect_to(resource_path(@service, @resource))
      else
        render(:edit, status: :bad_request)
      end
    end

    def destroy
      @resource.destroy
      redirect_to(resources_path(@service))
    end

    private

    def find_and_authorize
      @resource = @service.resources.
                  find_by!(id: params[:id], resource_type: resource_type)
      authorize(@resource)
    end

    def load_service
      @service = service_finder.find(params[:service_id])
      authorize(@service, :show?)
    end

    def service_finder
      action_name == 'show' ? Service.includes(:access_methods) : Service
    end

    def resource_type
      raise 'Need resource type'
    end

    def resource_path(_service, _resource)
      raise 'Need resource path'
    end

    def resources_path(_service)
      raise 'Need resource path'
    end

    def create_and_authorize_resource
      @resource = Resource.new(permitted_attributes(Resource))
      @resource.service = @service
      @resource.resource_type = resource_type
      @resource.resource_managers.build(user: current_user)
      authorize(@resource)
    end
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  before_action :find_and_authorize,
                only: [:update, :destroy]

  def index
    @services = policy_scope(Service).order(:name)
  end

  def new
    @service = Service.new
  end

  def show
    @service = Service.includes(:access_methods).find(params[:id])
    authorize(@service)
  end

  def create
    @service = Service.new(permitted_attributes(Service).merge(access_method_params))
    @service.users << current_user

    if @service.save
      redirect_to(services_path)
    else
      render(:new)
    end
  end

  def edit
    @service = Service.includes(:access_methods, :users).find(params[:id])
    authorize(@service)
  end

  def update
    if @service.update_attributes(permitted_attributes(@service).merge(access_method_params))
      redirect_to(service_path(@service))
    else
      render(:edit)
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path
  end

  private

  def access_method_params
    { access_methods: present_access_methods + new_access_methods }
  end

  def present_access_methods
    @service ? @service.access_methods.where(id: params[:service][:access_method_ids]) : []
  end

  def new_access_methods
    new_access_method_names =
      (params[:service][:access_method_ids] || []).
      uniq.
      select do |value|
        value.present? &&
          AccessMethod.where(id: value).
            or(AccessMethod.where(name: value, service: [nil, @service&.id])).
            empty?
      end
    new_access_method_names.map { |name| AccessMethod.new(name: name) }
  end

  def find_and_authorize
    @service = Service.find(params[:id])
    authorize(@service)
  end
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
  def pill_list(collection)
    content_tag(:ul, class: 'list-inline') do
      (collection || []).map do |item|
        name = block_given? ? yield(item) : item.name
        concat(
          content_tag(
            :li, content_tag(:span, name, class: %w[label label-info label-xs])
          )
        )
      end
    end
  end

  def global_access_methods_hint
    global_access_methods = AccessMethod.global.pluck(:name)
    return if global_access_methods.blank?
    I18n.t('simple_form.hints.service.access_methods',
           globals: global_access_methods.join(', '))
  end
end

app/views/services/local_policies/_edit_help.en.haml
.x_panel
  .x_title
    %h2 Editing policy details
    .clearfix
  .x_content
    %p
      Here you can edit the name of the global policy and the associated service path.
      The path attibute can contain a wildcard character at the end to match any path part
      (e.g. http://host.com/path/*).

app/views/services/local_policies/_index_help.en.haml
.x_panel
  .x_title
    %h2 Local policies
    .clearfix
  .x_content
    %p
      This is a list of local security policies defined for the service.
      Local policies can be managed through the Process API (see the
      %b Help/Resource policies
      section in the left-hand panel) or by the service owner.
    %p
      Local policies are intended to be controlled directly by the service
      using REST API. In emergency situation service owner is also able to manage
      local policies but it should be made with care, since it can destroy service
      permissions system.

app/views/services/local_policies/_new_help.en.haml
.x_panel
  .x_title
    %h2 Creating a new local policy
    .clearfix
  .x_content
    %p
      To create a new local policy for the whole service or for one of its
      resources, you need to specify the policy name and path. The path
      attribute is appended to the service URI (e.g.
      %b http://my.service.com/path
      ) and restricts the applicability of this policy to the given path.
      The path attibute can contain a wildcard character at the end to match any path part
      (e.g. http://my.service.com/path/*).

app/views/services/local_policies/_resource.html.haml
%tr
  %td= link_to(resource.name || resource.path, service_local_policy_path(@service, resource))
  %td= resource.uri
  %td
    = link_to(edit_service_local_policy_path(@service, resource),
      title: t('.edit'), class: 'edit') do
      = icon('edit')
    = link_to(service_local_policy_path(@service, resource), title: t('.remove'), method: :delete,
        data: {confirm: t('are_you_sure')}, class: 'delete') do
      = icon('remove')

app/views/services/local_policies/_show_help.en.haml
.x_panel
  .x_title
    %h2 Policy management window
    .clearfix
  .x_content
    %p
      You can create individual access rules for this policy by selecting users or user groups and
      specifying which access methods are to be made available to these users (or groups). Access methods offered
      by the service are defined in the service properties window - they may include standard REST methods such as
      %b GET, POST, DELETE
      etc., or more sophisticated methods tailored to your service.

app/views/services/local_policies/edit.html.haml
%h1= t('.title', service_name: @service.name, name: @resource.name)
.col-md-8
  = render('services/show_layout') do
    .x_title
      %h2
        = @resource.name
        %small= t 'services.local_policies.edit.subtitle'

      %ul.nav.navbar-right.panel_toolbox
        %li
          = link_to(service_local_policy_path(@service, @resource), class: 'back') do
            = icon('hand-o-left', title: t('services.local_policies.edit.back'))
      .clearfix
    .x_content
      = render partial: 'resources/form',
               locals: { resource: resource, url: service_local_policy_path(@service, @resource) }
.col-md-4
  = render 'edit_help'

app/views/services/local_policies/index.html.haml
%h1
  = t('.title', service_name: @service.name)
  .pull-right
    = link_to(new_service_local_policy_path(@service),
      title: t('services.local_policies.index.add'),
      class: 'btn btn-success') do
      = icon('plus', t('.add'))
.col-md-8
  = render('services/show_layout') do
    - if @resources.exists?
      %table.table
        %thead
          %tr
            %th= t('services.local_policies.index.policy_name')
            %th= t('services.local_policies.index.policy_uri')
            %th
          = render partial: 'resource', collection: @resources
    - else
      %p= t('services.local_policies.index.nothing')
.col-md-4
  = render "index_help"

app/views/services/local_policies/new.html.haml
%h1= t('.title', service_name: @service.name)
.col-md-8
  = render('services/show_layout') do
    .x_title
      %h2
        = t '.title'
        %small= t '.subtitle'

      %ul.nav.navbar-right.panel_toolbox
        %li
          = link_to(service_local_policies_path(@service), class: 'back') do
            = icon("hand-o-left", title: t('.back_to_index'))
      .clearfix
    .x_content
      = render partial: 'resources/form',
               locals: { resource: resource, url: service_local_policies_path(@service) }
.col-md-4
  = render 'new_help'

app/views/services/local_policies/show.html.haml
%h1= t('.title', service_name: @model.service.name, name: @model.resource.name)
.col-md-8
  = render('services/show_layout') do
    .x_title
      %h2
        = @model.resource.name
        %small= @model.resource.uri

      %ul.nav.navbar-right.panel_toolbox
        %li
          = link_to(service_local_policies_path(@model.service), class: 'back') do
            = icon("hand-o-left", title: t('services.local_policies.show.back'))
        %li
          = link_to(edit_service_local_policy_path(@model.service, @model.resource), class: 'edit') do
            = icon('edit', title: t('edit'))
        %li
          = link_to(service_local_policy_path(@model.service, @model.resource),
            method: :delete, class: 'delete',
            data: { confirm: t('are_you_sure') }) do
            = icon('remove', title: t('remove'))
      .clearfix
    .x_content#access-policies
      = render('access_policies/index', model: @model)
      = render('access_policies/form', model: @model)
.col-md-4
  = render 'services/local_policies/show_help'
  = render 'resources/managers'